### ISSUE TITLE
Improvements on elegant_mkstyle.txt

### ISSUE THREAD

**Issue by MertGunduz** [MertGunduz/mkhtml#11]
Hello contributor,

We are generating html documents and inserting our boilerplate stylesheets to our output files.

We need some improvements on elegant_mkstyle.txt 

Folder: cssgenerators/elegant_mkstyle.txt

**Comment by GorkemYilmaz325** [comment]
Hello i can do it

**Comment by MertGunduz** [comment]
> Hello i can do it

Hey @GorkemYilmaz325 

Thanks a lot, I assigned you for this task! ❤️ 🏆
