### ISSUE TITLE
need cartoonish stylesheet

### ISSUE THREAD

**Issue by MertGunduz** [MertGunduz/mkhtml#3]
Hello contributor,

we are using stylesheets (cssgenerators folder) as a boilerplate generation tool for html outputs.

And we need a cartoonish looking stylesheet for this tags, you can use this code snippet as a blank stylesheet:

```html
<style>
    html {

    }

    body {

    }

    h1 {

    }

    h2 {

    }

    h3 {

    }

    h4 {

    }

    h5 {

    }

    h6 {

    }

    p {

    }

    ol, ul {

    }

    li {

    }

    table {

    }

    th {

    }

    td {

    }
</style>
```

**Comment by nt-kleamm** [comment]
Hi Mert, I have an idea that might work pretty well, I am going to commit it soon!

**Comment by MertGunduz** [comment]
@nt-kleamm Thanks a lot @nt-kleamm 

I assigned you to this issue! ❤️
