### ISSUE TITLE
need elegant looking stylesheet

### ISSUE THREAD

**Issue by MertGunduz** [MertGunduz/mkhtml#4]
Hello contributor,

we are using stylesheets (cssgenerators folder) as a boilerplate generation tool for html outputs.

And we need a elegant looking stylesheet for this tags, you can use this code snippet as a blank stylesheet:

```html
<style>
    html {

    }

    body {

    }

    h1 {

    }

    h2 {

    }

    h3 {

    }

    h4 {

    }

    h5 {

    }

    h6 {

    }

    p {

    }

    ol, ul {

    }

    li {

    }

    table {

    }

    th {

    }

    td {

    }
</style>
```

**Comment by rremii** [comment]
Hey,i'll do it :D
