### ISSUE TITLE
need hacker scene looking stylesheet 

### ISSUE THREAD

**Issue by MertGunduz** [MertGunduz/mkhtml#6]
Hello contributor,

we are using stylesheets (cssgenerators folder) as a boilerplate generation tool for html outputs.

And we need a elegant looking stylesheet for this tags, you can use this code snippet as a blank stylesheet:

```html
<style>
    html {

    }

    body {

    }

    h1 {

    }

    h2 {

    }

    h3 {

    }

    h4 {

    }

    h5 {

    }

    h6 {

    }

    p {

    }

    ol, ul {

    }

    li {

    }

    table {

    }

    th {

    }

    td {

    }
</style>
```

**Comment by nt-kleamm** [comment]
Hey Mert, I can work on it, I'll make a css template like you want, I hope it will work, your welcome.

**Comment by MertGunduz** [comment]
@nt-kleamm 

Nice, thanks a lot @nt-kleamm I assigned you for this project! ❤️
