### ISSUE TITLE
new css style needed

### ISSUE THREAD

**Issue by MertGunduz** [MertGunduz/mkhtml#9]
Hello contributor,

we are using stylesheets (cssgenerators folder) as a boilerplate generation tool for html outputs.

And we need a random stylesheet for this tags, you can use this code snippet as a blank stylesheet:

```html
<style>
    html {

    }

    body {

    }

    h1 {

    }

    h2 {

    }

    h3 {

    }

    h4 {

    }

    h5 {

    }

    h6 {

    }

    p {

    }

    ol, ul {

    }

    li {

    }

    table {

    }

    th {

    }

    td {

    }
</style>
```

**Comment by SlothShino** [comment]
Hi, i can do it =)

**Comment by MertGunduz** [comment]
@SlothShino Thanks for the contribution request! ❤️ 

I assigned you for this task 👍🏻

**Comment by SlothShino** [comment]
Thank you! I'll keep in touch =)
